### ISSUE TITLE
Method not implemented exception when calling configurationModify.serverSettings.modifySettings()

### ISSUE THREAD

**Issue by steve-todorov** [RocketChat/Rocket.Chat.Apps-engine#67]
I have written a small app which replaces chat messages which contain specific strings with links to our issue tracker. When you install the `app`, it has a `URL` which you need to provide. Once you have updated the url in the `onSettingUpdated` will send a request to the issue tracker's `rest api` and fetch all of the active projects so that when you write `ABC-123` it would replace it with a link to the issue.

The issue I'm facing is that when `RocketChat` restarts, the `projects` are not preserved. I decided to create another configuration setting in the `extendConfiguration` which is `hidden` and store the data there, but I'm receiving the following exception:

```
  "{\"stack\":\"Error: Method not implemented.
    at Promise.asyncApply (/app/bundle/programs/server/packages/rocketchat_apps.js:1245:13)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
\",\"message\":\"Method not implemented.\"}"
```

Am I doing it wrong or is this really not implemented? Is there any actual documentation of how all this should be working - I don't seem to be finding it on the website? 

Here's my code:
```
import {IConfigurationExtend,IConfigurationModify,IEnvironmentRead,IHttp,IHttpResponse,ILogger,IMessageBuilder,IPersistence,IRead} from '@rocket.chat/apps-engine/definition/accessors';
import {App} from '@rocket.chat/apps-engine/definition/App';
import {IMessage, IPreMessageSentModify} from '@rocket.chat/apps-engine/definition/messages';
import {IAppInfo} from '@rocket.chat/apps-engine/definition/metadata';
import {ISetting, SettingType} from "@rocket.chat/apps-engine/definition/settings";

export class YouTrackApp extends App implements IPreMessageSentModify {

    readonly SETTING_YOUTRACK_URL = 'Youtrack_URL';
    readonly SETTING_YOUTRACK_PROJECTS = 'Youtrack_PROJCETS';

    private projects = [];

    protected constructor(info: IAppInfo, logger: ILogger) {
        super(info, logger);
    }

    public async checkPreMessageSentModify(message: IMessage, read: IRead, http: IHttp): Promise<boolean> {
        const url = (await read.getEnvironmentReader().getSettings().getValueById(this.SETTING_YOUTRACK_URL));

        if (url !== null && url !== '' && this.projects.length > 0 && message.text) {
            const match = message.text.match(this.getRegex());
            return match !== null && match.length > 0;
        }

        return false;
    }

    public async executePreMessageSentModify(message: IMessage, builder: IMessageBuilder, read: IRead, http: IHttp, persistence: IPersistence): Promise<IMessage> {
        const url = (await read.getEnvironmentReader().getSettings().getValueById(this.SETTING_YOUTRACK_URL));

        if (!url || this.projects.length < 1) {
            return message;
        }

        if (message.text) {
            const regex = this.getRegex();
            const match = Array.from(new Set(message.text.match(regex)));

            if (match && match.length > 0) {

                let text = message.text;

                for (let i = 0; i < match.length; i++) {
                    const issue = match[i];
                    let title = await this.getIssueSummary(issue, url, http);

                    // This could happen on error or if the issue is private.
                    if (title === false) {
                        title = '';
                    }

                    this.getLogger().debug(title);
                    this.getLogger().debug(message.text);

                    // @ts-ignore
                    text = text.replace(new RegExp(issue, 'gi'), '[' + issue.toUpperCase() + ' ' + title + '](' + url + '/issue/' + issue + ')');
                }

                return builder.setText(text).getMessage();
            }
        }

        return message;
    }

    public async onSettingUpdated(setting: ISetting, configurationModify: IConfigurationModify, read: IRead, http: IHttp): Promise<void> {
        if (setting.id === this.SETTING_YOUTRACK_URL) {
            // Ignore this error - setting is actually an array of settings.
            const url = setting.value;

            this.getLogger().debug(setting);
            this.getLogger().debug(setting.value);

            read.getPersistenceReader().read('test');

            if (url !== null && url !== '') {
                const fetchProjects = await this.getProjects(url, http);

                if (fetchProjects) {
                    this.projects = fetchProjects;
                } else {
                    this.projects = [];
                }
            } else {
                this.projects = [];
            }

            await configurationModify.serverSettings.modifySetting({
                id: this.SETTING_YOUTRACK_PROJECTS,
                type: SettingType.STRING,
                value: JSON.stringify(this.projects),
                packageValue: null,
                required: false,
                public: false,
                hidden: true,
                i18nLabel: ''
            });

            this.getLogger().debug("Projects:");
            this.getLogger().debug(this.projects);
            this.getLogger().debug("Regex matcher:");
            this.getLogger().debug(this.getRegex().toString());
        }
    }

    private getRegex() {
        const expr = '(' + this.projects.join('|') + ')-([0-9]+)';
        return new RegExp(expr, 'gi');
    }

    private async getIssueSummary(issue, url, http: IHttp) {
        const restUrl = url + '/rest/issue/' + issue;

        const response = await http
            .get(restUrl, {headers: {"accept": "application/json"}})
            .then((response: IHttpResponse) => {
                try {
                    if (response.content) {
                        const summary = JSON.parse(response.content).field.filter(v => v.name === 'summary').map(v => v.value);
                        this.getLogger().debug("Youtrack issue (" + issue + ") summary retrieved: ", summary);
                        return summary;
                    } else {
                        this.getLogger().error("Response content cannot be parsed!");
                        this.getLogger().error(response.content);

                        return false;
                    }
                } catch (e) {
                    this.getLogger().error("Failed to parse response from " + restUrl);
                    this.getLogger().error(e);

                    return false;
                }
            }, (reason: any) => {
                this.getLogger().error("Failed to request " + restUrl);
                this.getLogger().error(reason);

                return false;
            });

        if (response !== false) {
            return response;
        } else {
            this.getLogger().error('Could not fetch youtrack issue summary!');
            return false;
        }
    }

    private async getProjects(url, http: IHttp) {
        const projectsUrl = url + '/rest/project/all';

        const response = await http
            .get(projectsUrl, {headers: {"accept": "application/json"}})
            .then((response: IHttpResponse) => {
                try {
                    if (response.content) {
                        this.getLogger().debug("Youtrack projects: ");
                        this.getLogger().debug(this.projects);

                        return JSON.parse(response.content).map(v => v.shortName);
                    } else {
                        this.getLogger().error("Response content cannot be parsed!");
                        this.getLogger().error(response.content);

                        return false;
                    }
                } catch (e) {
                    this.getLogger().error("Failed to parse response from " + projectsUrl);
                    this.getLogger().error(e);

                    return false;
                }
            }, (reason: any) => {
                this.getLogger().error("Failed to request " + projectsUrl);
                this.getLogger().error(reason);

                return false;
            });

        if (response !== false) {
            return response;
        } else {
            this.getLogger().error('Could not fetch youtrack projects!');
            return false;
        }
    }

    protected async extendConfiguration(configuration: IConfigurationExtend, environmentRead: IEnvironmentRead): Promise<void> {
        await configuration.settings.provideSetting({
            id: this.SETTING_YOUTRACK_URL,
            type: SettingType.STRING,
            packageValue: null,
            required: true,
            public: false,
            i18nLabel: this.SETTING_YOUTRACK_URL,
            i18nDescription: 'Youtrack_URL_Description',
        });

        await configuration.settings.provideSetting({
            id: this.SETTING_YOUTRACK_PROJECTS,
            type: SettingType.STRING,
            packageValue: null,
            required: false,
            public: false,
            hidden: true,
            i18nLabel: ''
        });

        try{
            this.projects = JSON.parse(await environmentRead.getServerSettings().getValueById(this.SETTING_YOUTRACK_PROJECTS))
        } catch (e) {
            this.projects = [];
        }
    }
}

```

**Comment by graywolf336** [comment]
`configurationModify.serverSettings` is for Rocket.Chat settings, not settings provided by the App. Thus, you shouldn't be using it when trying to update your own setting. But yes, updating the settings provided by the Rocket.Chat server is not yet implemented ([see here](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-apps/server/bridges/settings.js#L69)). As for documentation, you can find that here: https://rocket.chat/Rocket.Chat.Apps-engine/

@rodrigok I'm leaving this open as a reminder that there are still methods on the server which need to be implemented.
