### ISSUE TITLE
Notifier typing causes error

### ISSUE THREAD

**Issue by nbak** [RocketChat/Rocket.Chat.Apps-engine#802]
App implements IPostMessageSent.
Permissions listed in app.json: `networking`, `message.write`, `persistence`, `slashcommand`

<details>
<summary>executePostMessageSent</summary>

```typescript
async executePostMessageSent(message: IMessage, read: IRead, http: IHttp, persistence: IPersistence, modify: IModify): Promise<void> {
    console.log(1);
    let stopTyping: (() => Promise<void>) | null = null;
    try {
        const appUser = (await read.getUserReader().getAppUser())!;
        console.log(2);
        stopTyping = await modify.getNotifier().typing({
            id: message.room.id,
            scope: TypingScope.Room,
            username: appUser.name,
        });
        console.log(3);
        await sleep(2000); // Custom sleep funciton
        console.log(4);
    } catch (e) {
        console.log(5);
    } finally {
        console.log(6);
        await stopTyping?.();
        console.log(7);
    }
}
```

</details>

Application log after message sent in chat
```
Subprocess stderr 1
Subprocess stderr 2
Subprocess stderr error: Uncaught (in promise) TypeError: Cannot create property 'logs' on string 'Result must exist for success Response objects'
        data.logs = logger.getLogs();
                 ^
    at Module.errorResponse (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/lib/messenger.ts:141:18)
    at main (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts:121:33)
    at eventLoopTick (ext:core/01_core.js:183:11)
```

Using `this.getLogger().log` instead of `console.log` leaves no logs saved/printed.
Calling `modify.getNotifier().notifyUser` in slash command works without errors.

Message `Result must exist for success Response objects` seems to be from [jsonrpc-lite](https://github.com/teambition/jsonrpc-lite/blob/c8c40997f46e84e88f5ff10e663c53dd7db2233d/jsonrpc.ts#L438), called from [this line](https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/7c32f9dc5a3515d7ce0f43a1451c6af01081c1de/deno-runtime/lib/messenger.ts#L99).

Apps Engine version: 1.45.0

Issue present in Rocket.Chat versions 6.10.x, 6.11.x, 6.12.0, 6.12.1.
In Rocket.Chat version 6.9.5 app works without errors.

**Comment by cuonghuunguyen** [comment]
Got the same issue on Rocket.Chat 6.12.1

```
Subprocess stderr error: Uncaught (in promise) TypeError: Cannot create property 'logs' on string 'Result must exist for success Response objects'
        data.logs = logger.getLogs();
                 ^
    at Module.errorResponse (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/lib/messenger.ts:141:18)
    at main (file:///app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts:121:33)
    at eventLoopTick (ext:core/01_core.js:183:11)
    ```
